# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: '6500043eb702036e5810aed3ed1d2ab117409b72'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent Configuration:
#
agents:
  perfmon:
      -
        local: yes
        hostname: nickwin8vm
        countersfile: perfmon_counters.txt
        # Set "debug: true" to see metrics in stdout instead of sent to New Relic"
        debug: false
        # Set "testrun: true" to use input from local text/html files. Only parses input once, then quits.
        testrun: false
        